### ISSUE TITLE
Mismatching documentation of supported extensions

### ISSUE THREAD

**Issue by stianlaa** [Paperspace/deploy-action#13]
Hi, Thanks for a useful pipeline action! A tiny issue I encountered

## Background
In your documentation you state that:
```
### File extensions
`.json`, `.jsonc`, `.toml`, `.yaml`, `.yml` are all supported.
```
However, upon using `.yml` I encountered `Unsupported file extension: .yml`

Inspecting the relevant code quickly:
```typescript
const parseByExt = (filePath: string) => {
  const ext = path.extname(filePath);
  const content = fs.readFileSync(filePath, "utf8");

  switch (ext) {
    case ".yaml":
      return YAML.parse(content);
    case ".toml":
      return TOML.parse(content);
    case ".jsonc":
      return JSONC.parse(content);
    case ".json":
      return JSON.parse(content);
    default:
      throw new Error(`Unsupported file extension: ${ext}`);
  }
};
```

## Desired behavior

It seems to me that either the documentation should be adjusted, or .yml should be supported. This isn't a huge deal but should also be a quick fix.

**Comment by brodeyn** [comment]
Hey @stianlaa ! Thanks for pointing this out. Will push a fix soon. :)

**Comment by waseembahralaseel-cell** [comment]
Tag a
